/**
 * Sound event identifiers — one per distinct game action/situation.
 * These are the stable keys used across all themes. Swap the theme,
 * the mapping from key → audio file changes, the keys stay the same.
 */
export enum SoundEvent {
  // Turn flow
  YourTurn = 'your_turn',
  OpponentTurn = 'opponent_turn',

  // Dice
  DiceRoll = 'dice_roll',

  // Movement
  TokenMove = 'token_move',
  PassGo = 'pass_go',

  // Landing — by property color group
  LandBrown = 'land_brown',
  LandLightBlue = 'land_light_blue',
  LandPink = 'land_pink',
  LandOrange = 'land_orange',
  LandRed = 'land_red',
  LandYellow = 'land_yellow',
  LandGreen = 'land_green',
  LandDarkBlue = 'land_dark_blue',

  // Landing — special spaces
  LandRailroad = 'land_railroad',
  LandUtility = 'land_utility',
  LandTax = 'land_tax',
  LandChance = 'land_chance',
  LandCommunityChest = 'land_community_chest',
  LandFreeParking = 'land_free_parking',
  LandGo = 'land_go',

  // Property transactions
  BuyProperty = 'buy_property',
  PayRent = 'pay_rent',
  CollectRent = 'collect_rent',

  // Building
  BuildHouse = 'build_house',
  BuildHotel = 'build_hotel',
  SellBuilding = 'sell_building',

  // Mortgage
  Mortgage = 'mortgage',
  Unmortgage = 'unmortgage',

  // Cards
  CardDraw = 'card_draw',

  // Auction
  AuctionStart = 'auction_start',
  AuctionBid = 'auction_bid',
  AuctionWin = 'auction_win',

  // Jail
  GoToJail = 'go_to_jail',
  GetOutOfJail = 'get_out_of_jail',

  // Trades
  TradeComplete = 'trade_complete',

  // Taxes
  TaxPaid = 'tax_paid',

  // End game
  Bankruptcy = 'bankruptcy',
  Victory = 'victory',
}

/**
 * A sound theme defines how each SoundEvent maps to audio.
 *
 * Two modes — pick one per theme:
 *   1. `files` + optional per-file `volume` overrides (simple, ~25 small files)
 *   2. `sprite` + `spriteMap` (one bundled file, best for mobile bandwidth)
 *
 * File values accept an array for codec fallback: Howler picks the first
 * format the browser supports. Always provide ['.webm', '.mp3'] for
 * maximum compatibility — WebM/Opus is smaller; MP3 is the iOS fallback.
 */
export interface SoundTheme {
  /** Unique identifier, e.g. 'classic' | 'starwars' */
  id: string;
  /** Display name shown in settings UI */
  name: string;

  // --- Individual files mode ---
  /** Map of SoundEvent → path(s). Array = codec fallback list. */
  files?: Partial<Record<SoundEvent, string | string[]>>;

  // --- Sprite mode (mutually exclusive with `files`) ---
  /** Path to the sprite audio file (provide [webm, mp3] for codec fallback) */
  sprite?: string | string[];
  /**
   * Howler sprite map: { key: [offset_ms, duration_ms] }
   * Generated by `audiosprite` CLI — see docs/sounds.md
   */
  spriteMap?: Partial<Record<SoundEvent, [number, number]>>;

  // --- Shared options ---
  /** Master volume for this theme (0–1, default 0.8) */
  masterVolume?: number;
  /** Per-event volume overrides (0–1) */
  volume?: Partial<Record<SoundEvent, number>>;
}
